import { Job } from "./app/generated/prisma";

export const fakeJobs: (Job & { skills: string[] })[] = [
  {
    id: "1",
    sourceUrl: "https://jobs.lever.co/openai/123",
    title: "Frontend Engineer",
    company: "OpenAI",
    location: "San Francisco, CA",
    employment: "Full-time",
    remoteType: "Hybrid",
    salaryMin: 140000,
    salaryMax: 180000,
    currency: "USD",
    description:
      "We are looking for a frontend engineer to build and optimize user-facing applications that interact with AI models.",
    aiSummary:
      "OpenAI is seeking a frontend engineer to improve user interfaces for AI applications. Hybrid role based in SF.",
    skills: ["React", "TypeScript", "TailwindCSS", "Next.js", "UX Design"],
    stage: null,
    userId: "dev_user_id",
    createdAt: new Date("2025-08-16T12:00:00Z"),
    postedAt: new Date("2025-08-15T12:00:00Z"),
  },
  {
    id: "7",
    sourceUrl: "https://jobs.spotify.com/777",
    title: "Mobile Engineer",
    company: "Spotify",
    location: "Boston, MA",
    employment: "Full-time",
    remoteType: "Remote",
    salaryMin: 120000,
    salaryMax: 150000,
    currency: "USD",
    description:
      "Join Spotify’s mobile team to deliver music to millions of users through native iOS and Android apps.",
    aiSummary:
      "Spotify is hiring a mobile engineer for its music app team. Fully remote position.",
    skills: ["Swift", "Kotlin", "React Native", "CI/CD", "Agile"],
    stage: null,
    userId: "dev_user_id",
    createdAt: new Date("2025-08-18T10:00:00Z"),
    postedAt: new Date("2025-08-17T10:00:00Z"),
  },
  {
    id: "8",
    sourceUrl: "https://jobs.meta.com/888",
    title: "Machine Learning Engineer",
    company: "Meta",
    location: "Menlo Park, CA",
    employment: "Full-time",
    remoteType: "Hybrid",
    salaryMin: 160000,
    salaryMax: 210000,
    currency: "USD",
    description:
      "Build intelligent systems that power Facebook and Instagram recommendation algorithms.",
    aiSummary:
      "Meta seeks an ML engineer for recommendation systems across its products. Hybrid in Menlo Park.",
    skills: ["Python", "PyTorch", "TensorFlow", "Data Engineering", "ML Ops"],
    stage: null,
    userId: "dev_user_id",
    createdAt: new Date("2025-08-19T09:15:00Z"),
    postedAt: new Date("2025-08-18T09:00:00Z"),
  },
  {
    id: "9",
    sourceUrl: "https://jobs.doordash.com/999",
    title: "DevOps Engineer",
    company: "DoorDash",
    location: "Austin, TX",
    employment: "Full-time",
    remoteType: "On-site",
    salaryMin: 110000,
    salaryMax: 130000,
    currency: "USD",
    description:
      "Manage cloud infrastructure and CI/CD pipelines for a fast-moving logistics platform.",
    aiSummary:
      "On-site DevOps position at DoorDash managing AWS and CI/CD systems.",
    skills: ["AWS", "Terraform", "Kubernetes", "Jenkins", "Monitoring"],
    stage: null,
    userId: "dev_user_id",
    createdAt: new Date("2025-08-20T14:00:00Z"),
    postedAt: new Date("2025-08-19T14:00:00Z"),
  },
  {
    id: "10",
    sourceUrl: "https://jobs.nvidia.com/1010",
    title: "Graphics Software Engineer",
    company: "NVIDIA",
    location: "Santa Clara, CA",
    employment: "Full-time",
    remoteType: "Hybrid",
    salaryMin: 135000,
    salaryMax: 160000,
    currency: "USD",
    description:
      "Work on cutting-edge real-time graphics tools and APIs used in gaming and AI simulations.",
    aiSummary:
      "NVIDIA is hiring a graphics engineer for real-time rendering. Hybrid in Santa Clara.",
    skills: [
      "C++",
      "DirectX",
      "Vulkan",
      "Shader Programming",
      "Real-Time Graphics",
    ],
    stage: null,
    userId: "dev_user_id",
    createdAt: new Date("2025-08-21T11:30:00Z"),
    postedAt: new Date("2025-08-20T11:30:00Z"),
  },
];
